version: 0.2

phases:
  install:
    runtime-versions:
      nodjs: latest
    commands:
      - echo "Installing something"
    pre_build:
      commands:
        - echo "We are in the build phase"
    build:
      commands:
        - echo "We are in the build block"
        - echo "We will run some tests"
        - grep -Fq "Congratulations" index.html
    post_build:
      commands:
        - echo "We are in the post build phase"